services:

  mongo:
    image: mongo
    restart: always
    logging:
      driver: none
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend-test:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    command: npm run lint
    restart: 'no'
    depends_on:
      mongo:
        condition: service_healthy

  backend:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3001:3000
    healthcheck:
      interval: 10s
      timeout: 2s 
      start_period: 15s 
      retries: 5 
      test: node healthcheck.js

  frontend-test:
    build:
      context: frontend
      dockerfile: ../Dockerfile.frontend
    command: yarn test:microfrontend
    network_mode: host
    restart: 'no'
    environment:
          CI: true
    depends_on:
      frontend:
        condition: service_healthy

  frontend:
    build:
      context: frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - 3000:3000
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    depends_on:
      backend:
        condition: service_healthy
      auth-microfrontend:
        condition: service_healthy
      profile-microfrontend:
        condition: service_healthy
      cards-microfrontend:
        condition: service_healthy
    healthcheck:
      interval: 10s
      timeout: 2s 
      start_period: 15s 
      retries: 5 
      test: node healthcheck.js

  auth-microfrontend:
    build:
      context: frontend/microfrontend/auth
      dockerfile: ../../../Dockerfile.auth.microfrontend
    ports:
      - 3002:3002
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      interval: 10s
      timeout: 2s 
      start_period: 15s 
      retries: 5 
      test: node healthcheck.js

  profile-microfrontend:
    build:
      context: frontend/microfrontend/profile
      dockerfile: ../../../Dockerfile.profile.microfrontend
    ports:
      - 3003:3003
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      interval: 10s
      timeout: 2s 
      start_period: 15s 
      retries: 5 
      test: node healthcheck.js

  cards-microfrontend:
    build:
      context: frontend/microfrontend/cards
      dockerfile: ../../../Dockerfile.cards.microfrontend
    ports:
      - 3004:3004
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      interval: 10s
      timeout: 2s 
      start_period: 15s 
      retries: 5 
      test: node healthcheck.js